// frontend/src/pages/Register/Register.tsx
import axios from 'axios';
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Link, useNavigate } from 'react-router-dom';
import { authService } from '../../services/auth.service';
import './Register.css';

// Esquema de validação equivalente aos Validators do Angular
const registerSchema = z.object({
  name: z.string().min(1, 'O nome é obrigatório.').min(3, 'O nome deve ter no mínimo 3 caracteres.'),
  email: z.string().min(1, 'O e-mail é obrigatório.').email('Informe um e-mail válido.'),
  password: z.string().min(1, 'A senha é obrigatória.').min(6, 'A senha deve ter pelo menos 6 caracteres.'),
  confirmPassword: z.string().min(1, 'A confirmação de senha é obrigatória.'),
}).refine((data) => data.password === data.confirmPassword, {
  message: 'As senhas não coincidem.',
  path: ['confirmPassword'],
});

type RegisterFormData = z.infer<typeof registerSchema>;

export const Register: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  const {
    register,
    handleSubmit,
    formState: { errors, touchedFields },
  } = useForm<RegisterFormData>({
    resolver: zodResolver(registerSchema),
    mode: 'onTouched', // Simula o comportamento do Angular (touched/dirty)
  });

  const onSubmit = async (data: RegisterFormData) => {
    setLoading(true);
    setErrorMessage('');
    setSuccessMessage('');

    try {
      await authService.register({
        name: data.name,
        email: data.email,
        password: data.password,
        role: 'USER',
      });

      setLoading(false);
      setSuccessMessage('Cadastro realizado com sucesso! Redirecionando...');
      
      setTimeout(() => {
        navigate('/login');
      }, 2000);
    } catch (err) {
      console.error(err);
      setLoading(false);
      if (axios.isAxiosError(err)) {
      // Se for um erro retornado pelo Axios (como 400, 404, 500)
        setErrorMessage(
        err.response?.data?.message || 'Erro ao realizar cadastro. Tente novamente.'
    );
  }   else if (err instanceof Error) {
      // Se for um erro do JavaScript
        setErrorMessage(err.message);
  }   else {
      // Caso ocorra algo inesperado
        setErrorMessage('Erro ao realizar cadastro. Tente novamente.');
  }
    }
  };

  return (
    <div className="register-container">
      <div className="platform-brand" aria-label="Freelance">
        <span className="platform-mark" aria-hidden="true">F</span>
        <span>FREELANCE</span>
      </div>

      <div className="register-card">
        <h2>Criar Conta</h2>
        <p className="subtitle">Preencha os dados abaixo para se cadastrar</p>

        {errorMessage && (
          <div className="alert alert-danger">
            {errorMessage}
          </div>
        )}

        {successMessage && (
          <div className="alert alert-success">
            {successMessage}
          </div>
        )}

        <form onSubmit={handleSubmit(onSubmit)}>
          {/* Campo Nome */}
          <div className="form-group">
            <label htmlFor="name">Nome Completo</label>
            <input
              id="name"
              type="text"
              placeholder="Seu nome completo"
              className={errors.name && touchedFields.name ? 'invalid' : ''}
              {...register('name')}
            />
            {errors.name && touchedFields.name && (
              <span className="error-text">{errors.name.message}</span>
            )}
          </div>

          {/* Campo E-mail */}
          <div className="form-group">
            <label htmlFor="email">E-mail</label>
            <input
              id="email"
              type="email"
              placeholder="seu.email@exemplo.com"
              className={errors.email && touchedFields.email ? 'invalid' : ''}
              {...register('email')}
            />
            {errors.email && touchedFields.email && (
              <span className="error-text">{errors.email.message}</span>
            )}
          </div>

          {/* Campo Senha */}
          <div className="form-group">
            <label htmlFor="password">Senha</label>
            <input
              id="password"
              type="password"
              placeholder="Mínimo de 6 caracteres"
              className={errors.password && touchedFields.password ? 'invalid' : ''}
              {...register('password')}
            />
            {errors.password && touchedFields.password && (
              <span className="error-text">{errors.password.message}</span>
            )}
          </div>

          {/* Campo Confirmação de Senha */}
          <div className="form-group">
            <label htmlFor="confirmPassword">Confirmar Senha</label>
            <input
              id="confirmPassword"
              type="password"
              placeholder="Repita sua senha"
              className={errors.confirmPassword && touchedFields.confirmPassword ? 'invalid' : ''}
              {...register('confirmPassword')}
            />
            {errors.confirmPassword && touchedFields.confirmPassword && (
              <span className="error-text">{errors.confirmPassword.message}</span>
            )}
          </div>

          {/* Botão Submit */}
          <button type="submit" disabled={loading} className="btn-submit">
            {loading ? 'Carregando...' : 'Cadastrar'}
          </button>
        </form>

        <div className="footer-links">
          <p>
            Já possui uma conta? <Link to="/login">Faça Login</Link>
          </p>
        </div>
      </div>
    </div>
  );
};

// frontend/src/app/features/auth/register/register.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { AbstractControl, FormBuilder, FormGroup, ReactiveFormsModule, ValidationErrors, Validators } from '@angular/forms';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);

  registerForm: FormGroup = this.fb.group(
    {
      name: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', [Validators.required]],
      role: ['', [Validators.required]]
    },
    { validators: this.passwordMatchValidator }
  );

  loading = false;
  errorMessage = '';
  successMessage = '';

  private passwordMatchValidator(control: AbstractControl): ValidationErrors | null {
    const password = control.get('password')?.value;
    const confirmPassword = control.get('confirmPassword')?.value;

    if (password && confirmPassword && password !== confirmPassword) {
      control.get('confirmPassword')?.setErrors({ passwordMismatch: true });
      return { passwordMismatch: true };
    }
    return null;
  }

  isFieldInvalid(fieldName: string): boolean {
    const field = this.registerForm.get(fieldName);
    return !!(field && field.invalid && (field.dirty || field.touched));
  }

  onSubmit(): void {
  if (this.registerForm.invalid) {
    this.registerForm.markAllAsTouched();
    return;
  }

  this.loading = true;
  this.errorMessage = '';
  this.successMessage = '';

  const { name, email, password } = this.registerForm.value;

  this.authService.register({ name, email, password, role: 'USER' }).subscribe({
    next: () => {
      this.loading = false;
      this.successMessage = 'Cadastro realizado com sucesso! Redirecionando...';
      setTimeout(() => {
        this.router.navigate(['/login']);
      }, 2000);
    },
    error: (err) => {
      console.error(err);
      this.loading = false;
      this.errorMessage = err?.error?.message || 'Erro ao realizar cadastro. Tente novamente.';
    }
  });
}
}
<div class="register-container">

  <div class="platform-brand" aria-label="Freelance">
    <span class="platform-mark" aria-hidden="true">F</span>
    <span>FREELANCE</span>
  </div>

  <div class="register-card">
    <h2>Criar Conta</h2>
    <p class="subtitle">Preencha os dados abaixo para se cadastrar</p>

    @if (errorMessage) {
      <div class="alert alert-danger">
        {{ errorMessage }}
      </div>
    }

    @if (successMessage) {
      <div class="alert alert-success">
        {{ successMessage }}
      </div>
    }

    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
      <!-- Campo Nome -->
      <div class="form-group">
        <label for="name">Nome Completo</label>
        <input
          id="name"
          type="text"
          formControlName="name"
          placeholder="Seu nome completo"
          [class.invalid]="isFieldInvalid('name')"
        />
        @if (isFieldInvalid('name')) {
          <span class="error-text">
            @if (registerForm.get('name')?.hasError('required')) {
              O nome é obrigatório.
            } @else if (registerForm.get('name')?.hasError('minlength')) {
              O nome deve ter no mínimo 3 caracteres.
            }
          </span>
        }
      </div>

      <!-- Campo E-mail --> 
      <div class="form-group">
        <label for="email">E-mail</label>
        <input
          id="email"
          type="email"
          formControlName="email"
          placeholder="seu.email@exemplo.com"
          [class.invalid]="isFieldInvalid('email')"
        />
        @if (isFieldInvalid('email')) {
          <span class="error-text">
            @if (registerForm.get('email')?.hasError('required')) {
              O e-mail é obrigatório.
            } @else if (registerForm.get('email')?.hasError('email')) {
              Informe um e-mail válido.
            }
          </span>
        }
      </div>

      <!-- Campo Senha -->
      <div class="form-group">
        <label for="password">Senha</label>
        <input
          id="password"
          type="password"
          formControlName="password"
          placeholder="Mínimo de 6 caracteres"
          [class.invalid]="isFieldInvalid('password')"
        />
        @if (isFieldInvalid('password')) {
          <span class="error-text">
            @if (registerForm.get('password')?.hasError('required')) {
              A senha é obrigatória.
            } @else if (registerForm.get('password')?.hasError('minlength')) {
              A senha deve ter pelo menos 6 caracteres.
            }
          </span>
        }
      </div>

      <!-- Campo Confirmação de Senha -->
      <div class="form-group">
        <label for="confirmPassword">Confirmar Senha</label>
        <input
          id="confirmPassword"
          type="password"
          formControlName="confirmPassword"
          placeholder="Repita sua senha"
          [class.invalid]="isFieldInvalid('confirmPassword')"
        />
        @if (isFieldInvalid('confirmPassword')) {
          <span class="error-text">
            @if (registerForm.get('confirmPassword')?.hasError('required')) {
              A confirmação de senha é obrigatória.
            } @else if (registerForm.get('confirmPassword')?.hasError('passwordMismatch')) {
              As senhas não coincidem.
            }
          </span>
        }
      </div>

      <!-- Botão Submit -->
      <button type="submit" [disabled]="loading" class="btn-submit">
        @if (loading) {
          Carregando...
        } @else {
          Cadastrar
        }
      </button>
    </form>

    <div class="footer-links">
      <p>Já possui uma conta? <a routerLink="/login">Faça Login</a></p>
    </div>
  </div>
</div>
