// frontend/src/app/features/auth/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);

  loginForm: FormGroup = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]]
  });

  loading = false;
  errorMessage = '';

  isFieldInvalid(fieldName: string): boolean {
    const field = this.loginForm.get(fieldName);
    return !!(field && field.invalid && (field.dirty || field.touched));
  }

  async onSubmit(): Promise<void> {
    if (this.loginForm.invalid) {
      this.loginForm.markAllAsTouched();
      return;
    }

    this.loading = true;
    this.errorMessage = '';

    const { email, password } = this.loginForm.value;

    try {
      await firstValueFrom(this.authService.login({ email, password }));
      this.router.navigate(['/home']);
    } catch (err: any) {
      console.error('Erro no login:', err);
      this.errorMessage = err?.error?.message || 'Email ou senha inválidos.';
    } finally {
      this.loading = false;
    }
  }
}

<main class="login-container">
  <div class="platform-brand" aria-label="Freelance">
    <span class="platform-mark" aria-hidden="true">F</span>
    <span>FREELANCE</span>
  </div>

  <section class="login-card" aria-labelledby="login-title">
    <h1 id="login-title">Acesse sua Conta</h1>
    <p class="subtitle">Informe seus dados para continuar.</p>

    @if (errorMessage) {
      <div class="alert alert-danger" role="alert">
        {{ errorMessage }}
      </div>
    }

    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="email">E-mail</label>
        <input
          id="email"
          type="email"
          formControlName="email"
          placeholder="seu.email@exemplo.com"
          autocomplete="email"
          [class.invalid]="isFieldInvalid('email')"
        />
        @if (isFieldInvalid('email')) {
          <span class="error-text">
            @if (loginForm.get('email')?.hasError('required')) {
              O e-mail é obrigatório.
            } @else if (loginForm.get('email')?.hasError('email')) {
              Informe um e-mail válido.
            }
          </span>
        }
      </div>

      <div class="form-group">
        <label for="password">Senha</label>
        <input
          id="password"
          type="password"
          formControlName="password"
          placeholder="Digite sua senha"
          autocomplete="current-password"
          [class.invalid]="isFieldInvalid('password')"
        />
        @if (isFieldInvalid('password')) {
          <span class="error-text">A senha é obrigatória.</span>
        }
      </div>

      <button type="submit" class="btn-submit" [disabled]="loading">
        @if (loading) {
          Entrando...
        } @else {
          Entrar
        }
      </button>
    </form>

    <div class="footer-links">
      <p>Não possui uma conta? <a routerLink="/register">Cadastre-se</a></p>
    </div>
  </section>
</main>

// frontend/src/pages/Login/Login.tsx
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Link, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { authService } from '../../services/auth.service';
import './Login.css';

// Schema do Zod equivalente aos Validators do Angular
const loginSchema = z.object({
  email: z
    .string()
    .min(1, 'O e-mail é obrigatório.')
    .email('Informe um e-mail válido.'),
  password: z.string().min(1, 'A senha é obrigatória.'),
});

type LoginFormData = z.infer<typeof loginSchema>;

export const Login: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const {
    register,
    handleSubmit,
    formState: { errors, touchedFields },
  } = useForm<LoginFormData>({
    resolver: zodResolver(loginSchema),
    mode: 'onTouched', 
  });

  const onSubmit = async (data: LoginFormData) => {
    setLoading(true);
    setErrorMessage('');

    try {
      await authService.login({
        email: data.email,
        password: data.password,
      });

      navigate('/home');
    } catch (err) {
      console.error('Erro no login:', err);

      if (axios.isAxiosError(err)) {
        setErrorMessage(
          err.response?.data?.message || 'Email ou senha inválidos.'
        );
      } else if (err instanceof Error) {
        setErrorMessage(err.message);
      } else {
        setErrorMessage('Email ou senha inválidos.');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="login-container">
      <div className="platform-brand" aria-label="Freelance">
        <span className="platform-mark" aria-hidden="true">F</span>
        <span>FREELANCE</span>
      </div>

      <section className="login-card" aria-labelledby="login-title">
        <h1 id="login-title">Acesse sua Conta</h1>
        <p className="subtitle">Informe seus dados para continuar.</p>

        {errorMessage && (
          <div className="alert alert-danger" role="alert">
            {errorMessage}
          </div>
        )}

        <form onSubmit={handleSubmit(onSubmit)}>
          {/* Campo E-mail */}
          <div className="form-group">
            <label htmlFor="email">E-mail</label>
            <input
              id="email"
              type="email"
              placeholder="seu.email@exemplo.com"
              autoComplete="email"
              className={errors.email && touchedFields.email ? 'invalid' : ''}
              {...register('email')}
            />
            {errors.email && touchedFields.email && (
              <span className="error-text">{errors.email.message}</span>
            )}
          </div>

          {/* Campo Senha */}
          <div className="form-group">
            <label htmlFor="password">Senha</label>
            <input
              id="password"
              type="password"
              placeholder="Digite sua senha"
              autoComplete="current-password"
              className={
                errors.password && touchedFields.password ? 'invalid' : ''
              }
              {...register('password')}
            />
            {errors.password && touchedFields.password && (
              <span className="error-text">{errors.password.message}</span>
            )}
          </div>

          {/* Botão Submit */}
          <button type="submit" className="btn-submit" disabled={loading}>
            {loading ? 'Entrando...' : 'Entrar'}
          </button>
        </form>

        <div className="footer-links">
          <p>
            Não possui uma conta? <Link to="/register">Cadastre-se</Link>
          </p>
        </div>
      </section>
    </main>
  );
};

export default Login;
